### ISSUE TITLE
The website documentation section should only refer to DTN

### ISSUE THREAD

**Issue by mkmelin** [thunderbird/thunderbird-website#154]
https://www.thunderbird.net/en-US/get-involved/#documentation

The link to https://wiki.mozilla.org/Thunderbird:Home is now first, but that page is basically, totally out of date. I would scrap it completely. In any case, the DTN link should be first.

We could maybe also have it in a list of entries
 - Thunderbird core development (link to DTN relevant section)
 - Thunderbird add-on development (link to DTN relevant section)
 - End user documentation (link to SUMO) #149

**Comment by Sancus** [comment]
I agree this section needs a rework to separate the types of documentation out. I don't think immediately removing the wiki link is a good idea. While it may be out of date for developer documentation, it has links to valuable stuff if you are trying to get an overview of the whole project.

Like: the status meeting page, the core team list, the electoral rolls, etc.

DTN is supposed to be for development, so information on stuff like release driving, governance, infrastructure, planning etc has to go somewhere else. Also while some parts of this page are old, I believe Wayne and others do still update the parts of the wiki that are relevant to them.

**Comment by justdave** [comment]
Looks like the wikimo page got updated since this was filed... the links there seem relevant to me now. (and many of them point to DTN)

**Comment by wsmwk** [comment]
See issue #201 and #202.  IIRC wiki mostly will be removed.  @ryanleesipes was going to work on implementing them.  So perhaps we close this issue


The whole documentation section is pretty thin. One thing in particular I remember is we don't have a pointer on how actually contribute to SUMO doc.

**Comment by MelissaAutumn** [comment]
We've re-worked out participation page. Please re-open if it's still not to everyones liking.
