### ISSUE TITLE
get-involved 2.0 overall update

### ISSUE THREAD

**Issue by wsmwk** [thunderbird/thunderbird-website#202]
follow up to issue #201

Note, there is inconsistency of how subitems/lists are presented.  In some cases it is preceded with a sentence ending in a period, and in others ending in a colon.  Suggest it should be consistent throughout the page.

The "Design" section looks odd / flows strangely horizontally.  It also feels short and incomplete.  I don't have specific recommendations but I'll bet someone can sort it out.  Also, should the UX topicbox be listed?

Mozilla have updated their references, so there may be new material we can learn from or draw from at https://www.mozilla.org/en-US/contribute/   Part of that is we may need the equivalent of  https://community.mozilla.org/en/activities/contribute-documentation/  and https://support.mozilla.org/en-US/get-involved/kb  (worthy of a separate ticket?)  Short term, "Support users asking for help" is misplaced under "Contributing to documentation"

We very much need more people to help other users in SUMO https://support.mozilla.org/en-US/get-involved/questions. (perhaps a separate ticket?)

In at least a couple places it would be helpful I think to point readers to the communications section - even though it is clearly on the same page. 

Some specific ideas to shorten/simplify and clarify.  

1. <s>If you would like to learn how</s> to contribute code to Thunderbird, check out our developer documentation. You will learn how to get the code, set any necessary configuration, <s>build the calendar,</s> rebuild after checking out new code, etc. It is a good read. <s>Don’t just skim it.</s>  For further advice and to communicate to other developers, see the venues listed under Communications.

2. <s>Thunderbird also relies on the code from mozilla-central.</s> See the build instructions for how to obtain all the code needed to build, including the mozilla-central repository.

3. All Thunderbird bugs live on <s>Mozilla’s</s> Bugzilla. <s>Bugzilla is a powerful tool and can be intimidating if you are not used to it. So</s> check out these pre-defined searches to test the waters:   (will create another issue to deal with the bugs subitems)

4. Under "Documentation" .. a) remove all references to wiki b) under "Where documentation lives" add references to SUMO KB c) under "Contributing to documentation" add references on how to improve the KB 

5. Move "Support users asking for help" from "Contributing to documentation" to its own new section and with additional details, until a larger discussion about the future of encouraging users to support each other.

**Comment by MelissaAutumn** [comment]
We now have https://www.thunderbird.net/participate/ 🎉
