### ISSUE TITLE
Donate to Thunderbird donate page has a "Invalid site key" Captcha error and donation is impossible.

### ISSUE THREAD

**Issue by jrpear** [thunderbird/thunderbird-website#203]
When I go to the "Donate to Thunderbird" [page](https://give.thunderbird.net/en-US/), there is a notification on the bottom of the page:
![captcha-error](https://user-images.githubusercontent.com/26498132/90927219-8515d480-e3a9-11ea-88d5-5ecbaf190bba.PNG)

As a result, when I go to donate in Firefox or Chrome, I'm unable to do so via PayPal or credit card. I click "Donate X$" at the bottom of the form and nothing happens.

**Comment by mkmelin** [comment]
Do you know what fixed it? I had an old PR, maybe for the same thing. https://github.com/mozilla/donate.mozilla.org/pull/2162

**Comment by Sancus** [comment]
> 
> 
> Do you know what fixed it? I had an old PR, maybe for the same thing. [mozilla/donate.mozilla.org#2162](https://github.com/mozilla/donate.mozilla.org/pull/2162)

Christopher @ MoFo fixed it. It was a typo in the actual key. I don't think there is a public commit because config details aren't stored in the public repo.
