### ISSUE TITLE
download buttons are inconsistently sized

### ISSUE THREAD

**Issue by Rexogamer** [thunderbird/thunderbird-website#281]
The Beta and Daily buttons are the same height and almost the same width, while the stable button is noticeably larger:
![image](https://user-images.githubusercontent.com/42586271/145616613-64f39000-ca29-4bc0-9a0d-618843de4599.png)
![image](https://user-images.githubusercontent.com/42586271/145616622-7a0b78a6-7597-4add-a9a1-bbef620d10aa.png)
![image](https://user-images.githubusercontent.com/42586271/145616630-bc05e2c7-16d0-4d87-88ce-c7370a9ce1ab.png)

**Comment by Sancus** [comment]
Not sure this is even a bug. I'm pretty sure the buttons are just sized to contain the text in them. It's a coincidence that the Beta/Daily ones are the same size.

**Comment by Alecaddd** [comment]
The height of the buttons is different since the "ESR" button is handled as primary and more important.
I can see how it feels strange in that context, maybe I can create a tiny variation for it.

**Comment by Sancus** [comment]
Maybe we can revisit this when we move the beta/daily buttons to the top.
