### ISSUE TITLE
2022 World Cup Fixture Calendar

### ISSUE THREAD

**Issue by joe-paulchell** [thunderbird/thunderbird-website#334]
A calendar file (ics) with the 2022 World Cup fixtures, including placeholders for Round of 16, Quarterfinals, Semifinals, and finals.

[WorldCup2022.zip](https://github.com/thundernest/thunderbird-website/files/9796132/WorldCup2022.zip)

**Comment by bogomil** [comment]
What usually happend with such calendars? Are they imported somewhere?

**Comment by MelissaAutumn** [comment]
Hey there! We've switched to generating holiday calendars via a third party service, and are no longer accepting community curated calendars. Traditionally we'd accept them by pull request. 

These generated calendars are available here: https://www.thunderbird.net/calendar/holidays/
