### ISSUE TITLE
add release notes link again

### ISSUE THREAD

**Issue by cadeyrn** [thunderbird/thunderbird-website#474]
I used to visit the Thunderbird home page to quicky access the release notes of the current version. Could you add the release notes link again?

**Comment by Sancus** [comment]
It will come back in some form eventually, not right now.

**Comment by Sancus** [comment]
Release notes will now be available on [the download page](https://www.thunderbird.net/en-US/thunderbird/all/), and also via the releases page which is linked as "Release Notes" in the footer.
