### ISSUE TITLE
Improve how users reach download links for Daily and Beta

### ISSUE THREAD

**Issue by emitche** [thunderbird/thunderbird-website#477]
If someone wants to download daily or beta, it is not obvious from the main page of Thunderbird where to access those links. The links can be found on the bottom of [Get Involved page](https://www.thunderbird.net/en-US/get-involved/), but a user would need to scan through a lot of text and sections to reach the download links.

<img width="527" alt="Screenshot 2023-07-17 at 1 37 48 PM" src="https://github.com/thundernest/thunderbird-website/assets/1853878/03588b08-71f2-4daa-8a6c-357965cc5df6">

**Comment by Sancus** [comment]
This will be improved when the rest of the site design is finished, yes.

**Comment by MelissaAutumn** [comment]
We now have a dropdown on the https://www.thunderbird.net/en-CA/thunderbird/all/ page which is available from clicking the "Download" in the navbar, or "Download & language options" on the frontpage.
