### ISSUE TITLE
Problem with the Dutch version of Supernova (Thunderbird)

### ISSUE THREAD

**Issue by J-HvW** [thunderbird/thunderbird-website#494]
Today ( 5 october 2023) Thunderbird was automatically updated to version 115.3.1 (32 bits), the Dutch version. However the window where an email message should displayed remains empty. Fortunately I have a separate email client (I use IMAP) on my phone which assures me that the messages are still there (and where I can read them). Also I am notified that there are new messages but as I cannot see these messages I cannot read them. How do I resolve this?

I tried looking at the Dutch help page which told me that there is something wrong with the page
![Screenshot 2023-10-05 at 11-28-32 Thunderbird — Er is hier niets!](https://github.com/thundernest/thunderbird-website/assets/35954797/02a3aab5-475e-4d27-b74a-6e8ffa53d86d) and to report it.

**Comment by MelissaAutumn** [comment]
Hey there, which help article did you find that had this broken link?

**Comment by Sancus** [comment]
No response in a while on this, closing it.
