### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by jcacqua** [thunderbird/thunderbird-website#516]
Hello
on this page : 
https://www.thunderbird.net/en-US/thunderbird/releases/

the link to 115.4.2 does not work
https://www.thunderbird.net/en-US/thunderbird/115.4.2/releasenotes/

There’s nothing here!
The page you are looking for doesn’t exist.
If you think this is a bug, you can [report an issue here](https://github.com/thundernest/thunderbird-website/issues).

**Comment by Sancus** [comment]
Fixed now, thanks for the report!
