### ISSUE TITLE
Page not found in latest 115 series of thunderbird. 

### ISSUE THREAD

**Issue by rajeev96299** [thunderbird/thunderbird-website#517]
Hi, we had observed there are no latest installers for 115.4.2 series in the thunderbird release notes page.

URL:
 https://www.thunderbird.net/en-US/thunderbird/releases/

Link to 115.4.2 series: https://www.thunderbird.net/en-US/thunderbird/115.4.2/releasenotes/

No release details found here!
The page you are looking for doesn’t exist.

**Comment by Sancus** [comment]
Fixed now. Thanks for the report!
