### ISSUE TITLE
EOY appeal donate button not clickable!

### ISSUE THREAD

**Issue by mkmelin** [thunderbird/thunderbird-website#530]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1865913

Go to https://www.thunderbird.net/en-CA/thunderbird/115.0/eoy/ - clicking the Donate button doesn't do antyhing

**Comment by MelissaAutumn** [comment]
Thanks for forwarding this. It was up on stage, but just needed to be pushed to prod. Thanks for the report!
