### ISSUE TITLE
 Bug 1870806 - Holiday EOY page is not showing localized version

### ISSUE THREAD

**Issue by jfx2006** [thunderbird/thunderbird-website#542]
When I open Thunderbird Daily with the bg(Bulgarian locale) from time to time the donation page appears: https://www.thunderbird.net/en-US/thunderbird/115.0/holidayeoy/

Since I am using the localized version, I'd expect to open this page: https://www.thunderbird.net/bg/thunderbird/115.0/holidayeoy/

From Mel:

> we never localize the /thunderbird path unless its /appeal, /eoy, or /beta-appeal

**Comment by MelissaAutumn** [comment]
The fix has been applied to both stage and prod, and we've restarted the servers. Thanks for the report!
