### ISSUE TITLE
Beta download page contains a confusing instruction

### ISSUE THREAD

**Issue by bogomil** [thunderbird/thunderbird-website#544]
The last line on the Beta download page says that there is a menu path  "≡ > Go > Mail Start Page..."  which do not exists in the "≡ " menu tree.

The customer needs to enable the menu toolbar and then  they can see the "Go" menu. Could you consider replacing it with the shortcut or an alternative approach.

Source: https://github.com/thunderbird/thunderbird-website/blob/43c4a9f444e48615d253b35bf93e070c12f2cd72/website/download/beta/index.html#L147

**Comment by bogomil** [comment]
@MelissaAutumn  - what could be a way for fixing this?

**Comment by wsmwk** [comment]
If it helps, rather than menu choices, the keyboard shortcuts are quite standard, but OS dependent:
* alt + home on Windows 
* alt + home on Linux
* option + home (home being Fn + left-arrow)

Reference https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird#w_moving-around-thunderbird

**Comment by bogomil** [comment]
I was thinking the same. I know SUMO can use variables for the OS, wondering if the website can do that. What about we say:
- Use the Mail Start Page shortcut listed here $link </b>to open a handy reference that documents several of the above items and more

and #link = [Go to Mail Start Page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-thunderbird#w_moving-around-thunderbird)

**Comment by bogomil** [comment]
i can do the PR, but I am not sure on how to add a new key for the translation

**Comment by MelissaAutumn** [comment]
Hey there @bogomil, apologies for not triaging this sooner, I was planning on looking at this later this week. We've got a larger redesign planned in the near future, so this information will probably change around or perhaps just link to a SUMO article. 

But if you'd like to give it a try we currently have some basic os detection for our download buttons you could use as a base: https://github.com/thunderbird/thunderbird-website/blob/master/assets/less/components/buttons.less#L206 
In case you're wondering where the .osx or .windows come from, there's some javascript that adds the platform to the <html> element.

Don't worry about updating the .po files for localization, they'll be handled by us on merge. 

Thanks!

**Comment by bogomil** [comment]
Change merged!
