### ISSUE TITLE
Update Ukrainian calendar

### ISSUE THREAD

**Issue by ostasevych** [thunderbird/thunderbird-website#548]
Please, update the Ukrainian holidays calendar, which includes the following updates:
- changes to the Christian holidays due to the official shift to Revised Julian calendar
- get rid of the official/non-official holidays which have been established in Soviet times, lately inherited and finally declined like Day of Militia et al.

The calendar includes Christian calculations up till 2030.

[UkraineHolidays_2023-2030.zip](https://github.com/thunderbird/thunderbird-website/files/13899476/UkraineHolidays_2023-2030.zip)

**Comment by bogomil** [comment]
@ostasevych  I believe Thunderbird now uses 3rd party provider for that and does not use PRs anymore.

**Comment by ostasevych** [comment]
The thing is that some apps use the tb calendars, in particular holiday calendar app of the Nextcloud. Therefore I PRed the updates to it.

**Comment by Sancus** [comment]
We're definitely not taking direct updates to the old ICS files anymore, but we should probably redirect the old calendars to the new ones at this point.

**Comment by ostasevych** [comment]
> We're definitely not taking direct updates to the old ICS files anymore, but we should probably redirect the old calendars to the new ones at this point.

So, what to do? There's a special web page, where users may get the national holiday calendars. It is not indicated that they are obsolete and this service will be stopped in some future.

![image](https://github.com/thunderbird/thunderbird-website/assets/5199030/67a19a99-32cd-4582-9ac5-9d32d920aad2)

**Comment by MelissaAutumn** [comment]
Hey there, apologies for not updating the calendar sooner. I will have a PR out later today with some updates from our calendar provider.

**Comment by MelissaAutumn** [comment]
This should be fixed now. If it's still not corrected, I will poke our calendar provider about it. Thanks!
