### ISSUE TITLE
Phantom character "s" on staging about page

### ISSUE THREAD

**Issue by milupo** [thunderbird/thunderbird-website#571]
Hi,

I found a phantom character "s" on the staging about page:

https://stage.thunderbird.net/hsb/about/

This is the Upper Sorbian page but the phantom "s" is displayed with other languages as well. It is on top in the first section, there is displayed "Organizacijas" for Upper Sorbian but the correct word is "Organizacija". On Pontoon the English string is "Organization".

Please correct it.

Thank you.

**Comment by MelissaAutumn** [comment]
Thanks for the report, I've called the phantom busters but it may be a day or so. 

Additionally I've spotted some text alignment issues that I'll need to patch up as well.

Cheers!

**Comment by MelissaAutumn** [comment]
This has been resolved, thanks for the report!

**Comment by milupo** [comment]
Yes, it's true. Thank you very much.
