### ISSUE TITLE
Caldata `Brazil-Holidays.ics` 404

### ISSUE THREAD

**Issue by avelino** [thunderbird/thunderbird-website#572]
**URL:** https://www.thunderbird.net/media/caldata/autogen/Brazil-Holidays.ics

Is the URL for holidays in Brazil (`ics`) giving a `404 error`, will it no longer be maintained?
I haven't tested the other ICS, but it probably has the same problem.

**Comment by MelissaAutumn** [comment]
Hello! Apologies its now at https://www.thunderbird.net/media/caldata/autogen/BrazilHolidays.ics

We normalized the names in preparation for some other changes, but haven't had the time to follow up on them.

Cheers,
Mel

**Comment by avelino** [comment]
@MelissaAutumn could have 301 (permanent redirect), so it doesn't break anyone using the old URL

**Comment by MelissaAutumn** [comment]
That was part of the plan, but it hasn't gone live yet 😅 

Apologies again!
