### ISSUE TITLE
Thunderbird 125.0

### ISSUE THREAD

**Issue by Gial333** [thunderbird/thunderbird-website#575]
In the Thunderbird release notes, there is version 125.0. The next page says: the page you are looking for doesn’t exist.

**Comment by Sancus** [comment]
Yes, we probably need a hack when we load major releases from Product Details.

https://github.com/thunderbird/thunderbird-website/blob/master/product_details.py#L69

Filter out versions 125.0, 126.0, and 127.0 -- we wont want those listed for now.
