### ISSUE TITLE
Survey landing page

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-website#577]
We need a small survey landing page at https://www.thunderbird.net/survey

This is just so that when we load the page in Thunderbird, we're not sending anybody to a 3rd party domain without their consent.

Copy is: `Hello from the Thunderbird team! We'd love if you could take approximately 5 minutes to share your experience using Thunderbird. Your anonymous feedback will help us identify our strengths and the areas we need to improve.

Thanks for helping us make Thunderbird better for everyone!`

Duplicating something like this with centered text and a single button to continue is fine. This is from SurveyMonkey.

![image](https://github.com/thunderbird/thunderbird-website/assets/479671/d91f668f-e27c-4620-aaed-14d25791c0d2)

This should be a one-time thing, the page can be reused for future surveys.

**Comment by MelissaAutumn** [comment]
Whens the deadline for this? We're sort of blocked by doing website updates until the new redesign is merged in. 

We can cherry pick this feature but it might get messy with all of the changes.

**Comment by Sancus** [comment]
We can do this after the new website goes live, lets say for May 20th.

**Comment by MelissaAutumn** [comment]
Initial draft up on https://stage.thunderbird.net/en-CA/survey/

cc @inattee

**Comment by inattee** [comment]
Nice! Maybe we should include a disclaimer: "_Please note: you will be redirected to Survey Monkey to complete this survey_"

**Comment by MelissaAutumn** [comment]
How does this look @inattee ?
<img width="1217" alt="image" src="https://github.com/thunderbird/thunderbird-website/assets/97147377/a1ef3e0e-d1ba-481b-86b2-14610b705293">

It will dynamically pull in the hostname depending on what the active survey link is, the underline is just for emphasis and isn't a link.

**Comment by inattee** [comment]
It's perfect - thank you!

**Comment by inattee** [comment]
Maybe a period at the end after 'survey'. Sorry, I missed that.

**Comment by MelissaAutumn** [comment]
Here's a live copy version: https://www.thunderbird.net/en-CA/survey/

The external link notice only shows up if we have a survey link set that points to an external domain. (or basically an absolute url.) So that's why its not showing up right now.

**Comment by inattee** [comment]
Thanks @MelissaAutumn! Survey has been localized and is ready to go: https://www.surveymonkey.com/r/69C9LSH

**Comment by R-Adrian** [comment]
might be a good idea to also add in the release notes a link to the survey, for people that actually want to see what new version release and the survey is about?

currently https://www.thunderbird.net/en-US/thunderbird/115.11.1/releasenotes/ 
has no such link... and i had to dig through Bugzilla to find a link to it and to this GitHub issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1898086

**Comment by Sancus** [comment]
> might be a good idea to also add in the release notes a link to the survey, for people that actually want to see what the new version release and the survey is about?
> 
> currently https://www.thunderbird.net/en-US/thunderbird/115.11.1/releasenotes/ has no such link... and i had to dig through Bugzilla to find a link to it and to this GitHub issue https://bugzilla.mozilla.org/show_bug.cgi?id=1898086

We actually don't want people finding the link on their own and filling in the survey, no. A few people doing it is no big deal. If many people do it(100+) the survey will become heavily selection biased and a lot less useful.

The reason we've done it the way we have is to get as close as possible to a proper random sampling of users.

**Comment by R-Adrian** [comment]
> The reason we've done it the way we have is to get as close as possible to a proper random sampling of users.

Since it is a publicly reachable survey, maybe also add an optional question about this in the survey itself?

Is it possible to modify the survey after deployment without resulting in a link change of the surveymonkey url?

Maybe a question along the lines of:
 "How did you arrive to this survey?"
 - Thunderbird prompted me about it
 - saw it in the release notes, searched for it and I accessed it directly
 - other (link to it was forwarded by someone else or other similar cases)

**Comment by MelissaAutumn** [comment]
Thanks for the suggestions! 

We're not too worried about outside traffic for this short-lived survey. However we'll take it into consideration for the next survey. 

Since this task is completed, I'll go ahead and close this issue.
