### ISSUE TITLE
Links from within the Thunderbird application

### ISSUE THREAD

**Issue by freaktechnik** [thunderbird/thunderbird-website#578]
There are a few links to thunderbird.net within Thunderbird itself. The ones I found that don't seem to work (or redirect) with the staging website are:

- https://www.thunderbird.net/get-involved/ -> https://stage.thunderbird.net/get-involved/
- https://www.thunderbird.net/features/ -> https://stage.thunderbird.net/features

**Comment by MelissaAutumn** [comment]
Thanks! I'll setup some redirects for now and we can hunt down those links once the site goes live. 😄

**Comment by MelissaAutumn** [comment]
Reference bugzilla ticket:
https://bugzilla.mozilla.org/show_bug.cgi?id=1896483

**Comment by MelissaAutumn** [comment]
This has been resolved afaik. Features will eventually link to the products page.
