### ISSUE TITLE
Redesign bug thread

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/thunderbird-website#579]
Here's a list of bugs with the new redesign:
- Various dead links:
  - [x] Contribute links to non-existent get-involved
  - [x] Donate links to get-involved
  - [x] Holiday calendar links to http://icalshare.com/
- Donation contact needs less white space
- Holiday Calendars needs to be less wide
- Formatting issues with thunderbird-notes

**Comment by inattee** [comment]
Going page by page:

### Mobile:
**Homepage:** 

Idea: Should we condense all of the different versions which show up on mobile devices for download into just one download button which goes to /en-US/thunderbird/all/ ? 
Considering it’s our homepage it looks really messy for mobile users and <1% of whom might be looking to download a desktop version of thunderbird on their mobile devices. 

**Footer**

 Does not render properly (at least on multiple iOS devices I tested).  ![IMG_E143E793D59C-1](https://github.com/thunderbird/thunderbird-website/assets/16977891/2c0c77b9-252e-4e0a-bc43-6d5d410d5ffb)

### Desktop

**Contact** 

- “Direct your inquiries to the people below” - "teams" might be better than people.
- Change contact email for Media to: [press@thunderbird.net](mailto:press@thunderbird.net)
- Change business contact email to: [partnerships@thunderbird.net](mailto:partnerships@thunderbird.net)

Contributors: 
- Change text to read “...learn how to get started by visiting our _Participate_ page.” 
- Link results in a 404: https://stage.thunderbird.net/en-US/contribute (? maybe 301 redirect that page to https://stage.thunderbird.net/en-US/participate/) 

**About**

- Privacy: Update privacy policy link to: https://www.mozilla.org/en-US/privacy/thunderbird/
- Voice: Is ‘Keep Reading…’ intended to link to something? Participate page, maybe? If not, we should remove it.

**Donate** 

Become a Supporter:
- Edit text to remove the word "free": ”...Our work is to provide open source apps that are secure, private _and available_ for users around the world…”.

FAQ Section:
- Too much scrolling to get here - reduce white space around the rocket and maybe make the rocket a bit smaller.
- Ways to give:  
Append Text: 
"**Additionally you can give** offline in USD by mailing a check or money order made payable to “MZLA Technologies Corp”. Mail to:
MZLA
PO Box 25718
Pasadena CA 91185-5718
Please include your email address on the memo line of your check to help us track and attribute your gift."

**Participate**
Top Links: 

[ ] - Translate - ‘currently translated into…”
[ ] - Promote: Missing: LinkedIn - https://www.linkedin.com/company/thunderbird-email/

- We reordered the blocks and now the text flow doesn’t really make sense.

- Take the first two sentences ("Volunteers create Thunderbird and ensure it is accessible throughout the world in dozens of languages. They write the documentation and answer the questions that help regular people use Thunderbird.") out of Contributor Experience and place them in the beginning under "We Need Your Talents".  Start Contributor Experience text with "Our volunteers come from ..."
- Remove “Read further to learn how.” out of the last Shape the Future section

**Releases Page**

- Intro text seemed strangely small, maybe it's a shorter paragraph than on previous pages or no header? Perhaps we could add “Release Notes” as a header?
- ‘Tell Us What You Think’ link on individual Release pages is going to SUMO and not Connect
- Select your version from the list below to see the release notes for it. Change to ‘Select your version below for the release notes.’
- Are there Release Notes for Beta?

**System Requirements Page**
Remove bullet on intro text to list, i.e., “Thunderbird will not run…” and “For optimal functionality…”
Check this page on mobile - it’s very tight ![IMG_8651](https://github.com/thunderbird/thunderbird-website/assets/16977891/f11a900d-7ae4-4321-879d-cd80c02dc8c6)

**Holiday Calendars Page**
Icalshare website timed out

**Comment by inattee** [comment]
![IMG_8651](https://github.com/thunderbird/thunderbird-website/assets/16977891/41966525-7be1-40f4-854c-13288f281803)
![IMG_E143E793D59C-1](https://github.com/thunderbird/thunderbird-website/assets/16977891/708b44d4-70e3-4fa5-9e11-53edde42852e)

**Comment by MelissaAutumn** [comment]
hey @inattee, thanks for the report!

* System requirements and release note pages are generated from https://github.com/thunderbird/thunderbird-notes/ they will happen a bit later as its a different repository
* I will fix the safari bugs, and broken links!
* Regarding the copy: did I miss anything from the copy google doc? I'm not seeing these changes in that doc.

**Comment by inattee** [comment]
Hey Mel, sorry totally forgot we had that copy page. I just updated the text there via suggestion comments.

**Comment by MelissaAutumn** [comment]
I've pushed up a fix for the Safari footer logo, and for the System Requirements overflow text. (Although the solution is currently not the greatest.)

Additionally I've fixed some broken links and added some redirects until we can fix them all (on start page, and elsewhere!)

**Comment by MelissaAutumn** [comment]
We've sent the copy edits from the doc out, and I've adjusted the styling issues. The release notes/system requirements will be coming a bit after launch. Thanks!
