### ISSUE TITLE
New website: Improvements for the links to the desktop section in the Participate page

### ISSUE THREAD

**Issue by babolivier** [thunderbird/thunderbird-website#580]
In https://stage.thunderbird.net/en-US/participate/, under Code > Desktop Development, the link for "Join the repository" directs to https://developer.thunderbird.net/thunderbird-development/codebase-overview. I don't believe this is the best landing point since it describes the file architecture within the repository, with no reference to where or how to explore the repository itself. So imo it's more of a guide document you'd refer to once you've already found a place to explore the repository. I think https://developer.thunderbird.net/thunderbird-development/getting-started might be a more fitting place to point people interested in checking out the repository for Thunderbird desktop.

Additionally, the "Say hello in Matrix" link goes to https://matrix.to/#/#maildev:mozilla.org:mozilla.org, which has an extraneous `:mozilla.org` at its end, which would make the room address in the URL invalid.

**Comment by MelissaAutumn** [comment]
Thanks! I've fixed the broken link, and applied your suggestion. We were having trouble finding the best places for the links to go, so I think getting-started is a good replacment for codebase-overview.
