### ISSUE TITLE
Beta Appeal

### ISSUE THREAD

**Issue by MelissaAutumn** [thunderbird/thunderbird-website#590]
Another beta appeal is coming up. Here's the tracking ticket.

Notes:
 * Link colour needs to be adjusted to `#1E4EAE`

**Comment by Sancus** [comment]
URL will be https://www.thunderbird.net/thunderbird/115.0/beta-appeal/

**Comment by wsmwk** [comment]
SGTM

**Comment by MelissaAutumn** [comment]
Final design ready, will begin work on it shortly.

<img width="1252" alt="image" src="https://github.com/thunderbird/thunderbird-website/assets/97147377/5da4ebd8-679c-4fd4-a092-a89389700429">
