### ISSUE TITLE
New Thunderbird home page should have direct links (or mention) to ATN / Add-ons?

### ISSUE THREAD

**Issue by RealRaven2000** [thunderbird/thunderbird-website#597]
Just got the newsletter with [Thunderbird's new web presence](https://www.thunderbird.net/en-US/) today, great work, looks fabulous. However I would like a mention of (or better, link to) the add-ons site please. It makes it look like Add-ons aren't part of the environment anymore.

My obvious place to look for Add-ons from here was to click on Resources >> Downloads, but there is no mention of Add-ons here either. At least an in-page link at the bottom would be helpful, because even an in-page search (Ctrl+F) with the words "extensions" or "add-ons" doesn't find anything. Can something be added to[ link to ATN](https://addons.thunderbird.net/) please? Or maybe make an interim page that explains the concept of Add-ons with the link, so you can keep engagement on the main domain, but link that from the front page in some obvious way. (Doesn't need to be all the way on the top, but somewhere on the page, definitely).

**Comment by MelissaAutumn** [comment]
Thanks for the feedback! There's still some specific product pages in the works too, but I'll also take this feedback into consideration. As one of the current maintainers of ATN, I also think it should be visible on our new website. It probably just slipped everyone's mind. :smile:

**Comment by Sancus** [comment]
Keep in mind that the main way to discover ATN is in Thunderbird. When you go to the website in your browser, you end up with a completely unusable installation experience. So I wouldn't want to direct *users* from the website to ATN. Developers, though, sure.

**Comment by MelissaAutumn** [comment]
We can probably add a small instructions pop-up to ATN with a link to SUMO. And for thunderbird.net we can add to the release information section or something. 

I'll let that marinate in my brain for a bit.

**Comment by MelissaAutumn** [comment]
It has been done: https://stage.thunderbird.net/en-CA/desktop/#third-party-ecosystem

Will be on prod next week.
