### ISSUE TITLE
"See All Releases" link not clickable on wide screens

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-website#599]
I have an "ultrawide" monitor and sometimes open websites using the full screen width. When visiting a release notes page, e.g. https://www.thunderbird.net/en-US/thunderbird/115.11.1/releasenotes/ the "See All Releases" link is not clickable. Presumably because the "page-separator-cover" element is drawn on top of the link (see screenshot).

![image](https://github.com/thunderbird/thunderbird-website/assets/218061/e6ef4c96-ec2e-41f5-87d4-b5e8afcb51bb)

**Comment by MelissaAutumn** [comment]
Should be fixed soon, thanks!
