### ISSUE TITLE
New website design lost the Thunderbird mission statement

### ISSUE THREAD

**Issue by clokep** [thunderbird/thunderbird-website#601]
The redesign of the Thunderbird website lost the mission statement. It would be great to get it added back. See #436 for context.

CC @thunderbird/thunderbird-council

**Comment by MelissaAutumn** [comment]
Mission statement:
https://thunderbird.topicbox.com/groups/planning/T82a50212b4d24bab-M1356dbf3bfbb40b9495c02cd

It will be linked off at the top paragraph of the About Us page as that page is pretty long.

**Comment by dannycolin** [comment]
> Mission statement: https://thunderbird.topicbox.com/groups/planning/T82a50212b4d24bab-M1356dbf3bfbb40b9495c02cd
> 
> It will be linked off at the top paragraph of the About Us page as that page is pretty long.

Will it link off to the mailinglist message or will the mission have its own page? I'd personally prefer the latter since the mailinglist shouldn't be used as a place to keep _permanent_ information.

**Comment by MelissaAutumn** [comment]
Hey @dannycolin 

Sorry I was clear, it'll be on its own page: https://stage.thunderbird.net/en-CA/about/mission-statement/ linked from https://stage.thunderbird.net/en-CA/about/

(And on the production environment hopefully by EOD)

**Comment by clokep** [comment]
Thanks for handling this! 🎉

**Comment by MelissaAutumn** [comment]
It's live!
https://www.thunderbird.net/en-US/about/mission-statement/

The link will appear on who we are page once the cache expires (there's also some slight style updates that are awaiting cache expiry), but the page is up via direct link.

**Comment by dannycolin** [comment]
Big thanks ❤️
