### ISSUE TITLE
Connection is not secure on new.thunderbird.net

### ISSUE THREAD

**Issue by sv-calin** [thunderbird/thunderbird-website#603]
[Report](https://github.com/webcompat/web-bugs/issues/138305) received via webcompat:

>URL: https://new.thunderbird.net/

>Browser / Version: Firefox 127.0
Operating System: Linux
Tested Another Browser: Yes Other

>Problem type: Something else
Description: SSL certificate expired
Steps to Reproduce:
The new.thunderbird.net uses a certificate expired on 22nd May.

>Please see: https://support.mozilla.org/en-US/questions/1450312

Screenshot:

![image](https://github.com/thunderbird/thunderbird-website/assets/107036654/a8697589-d71f-43b7-b6d6-2df745631ba0)

**Comment by MelissaAutumn** [comment]
We've turned off new for now.
