### ISSUE TITLE
"Explore Features" Button leads to dead link

### ISSUE THREAD

**Issue by heliophane** [thunderbird/thunderbird-website#604]
Howdy all!

Not a big deal, but just wanted to let y'all know that the "Explore Features" button in thunderbird leads to a dead page at the moment.
![image](https://github.com/thunderbird/thunderbird-website/assets/35747043/0e91ad9d-638a-4fdb-a6ef-378a8d32ee81)

![image](https://github.com/thunderbird/thunderbird-website/assets/35747043/b2578b65-3a70-4309-93c0-7cfbdb81d879)

**Comment by wsmwk** [comment]
@MelissaAutumn I can confirm, coming from "Account Central" fails.

**Comment by Sancus** [comment]
Probably need a per-locale redirect for `/features/` in [builder.py](https://github.com/thunderbird/thunderbird-website/blob/master/builder.py#L440) - also maybe move those htaccess rules to settings.py so they're not buried and it's easier to add/change.

**Comment by MelissaAutumn** [comment]
I don't believe we have a features page anymore. I'll add a redirect to home on monday until our product pages are ready.

**Comment by wsmwk** [comment]
Help >  Features  is currently going to "home" via https://www.thunderbird.net/features.  Whatever is chosen, Account Central and help menu should match.

At one time we had a what's new menu item but it was removed.
