### ISSUE TITLE
"There's Nothing Here" page opens when Thunderbird starts

### ISSUE THREAD

**Issue by am9417** [thunderbird/thunderbird-website#605]
After update, web page with the given title opens.

Link points to https://www.thunderbird.net/en-US/thunderbird/127.0/whatsnew/?locale=en-US&version=127.0&channel=release&oldversion=125.0

Also, Thunderbird's Message view shows the following error page, even though I have not updated the Thunderbird to some unsupported version:

![kuva](https://github.com/thunderbird/thunderbird-website/assets/10899115/d0d69711-ae45-45da-80d0-d9467ede5dc2)

**Comment by MelissaAutumn** [comment]
Hi there! 

Did you download Thunderbird from Thunderbird.net or from an app store (e.g. Windows Store, Flathub, a linux distribution repository?) 

The latest release version is 115, and the latest beta is 128 iirc. We are undergoing testing of a monthly release version, but as the start page says, its not ready for public consumption.

**Comment by am9417** [comment]
I'm using Windows. I should have downloaded it from Thunderbird.net, and not recall doing any updates manually recently

LähetettyOutlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by am9417** [comment]
I used the link in that message to download the latest stable version of Thunderbird. All my profile information dissappeared... 😞 

![kuva](https://github.com/thunderbird/thunderbird-website/assets/10899115/180f30f6-3a76-4883-8e02-b5a67256bd8b)

"Lisätietoja" (en: "More information") link will point to https://support.mozilla.org/fi/kb/unable-launch-older-version-profile

**Comment by MelissaAutumn** [comment]
Hey there, apologies for the delay. Unfortunately profiles aren't backwards compatible, it'd be nice if they were but I believe there's a lot of values outside our control that make it impossible. 

The next ESR is coming out soon so if you want to stay on your 127 build until 128 comes out, I believe that should work but I can't say for certain. If you need help with anything we have some lovely volunteers on Matrix (https://matrix.to/#/#thunderbird:mozilla.org), as well as support.mozilla.org (https://support.mozilla.org/en-US/products/thunderbird).
