### ISSUE TITLE
LinkedIn link redirects to home page

### ISSUE THREAD

**Issue by joetor5** [thunderbird/thunderbird-website#606]
Hi!

On the participate page (Promote section), the LinkedIn link redirects to the home page.

https://www.thunderbird.net/en-US/participate/

<img width="599" alt="tb-screenshot" src="https://github.com/thunderbird/thunderbird-website/assets/171155169/57c9de00-5e80-40ff-b851-609c95624164">

The 'participate.promote.linkedin' key is missing on URL_MAPPINGS in settings.py, hence the current rendering.

If you could assign this to me, that would be great!

**Comment by MelissaAutumn** [comment]
Thanks for the patch! 

I just realized I accidentally put it under support. So I fixed that as well. 😄
