### ISSUE TITLE
Temporary "warning" start page for Monthly Releases while in testing phase

### ISSUE THREAD

**Issue by jfx2006** [thunderbird/thunderbird-website#612]
Need something like [earlybird](https://github.com/thunderbird/thunderbird-website/tree/master/sites/start.thunderbird.net/earlybird) for the monthly releases while they're in the unsupported test phase for tracking purposes.

This is the file I'm currently using that's embedded in the app.
[release-candidate.html.txt](https://github.com/user-attachments/files/16070269/release-candidate.html.txt)

I just need the URL for whatever gets created.

**Comment by MelissaAutumn** [comment]
Thanks I can get it to you early next week if that's okay. Otherwise I can rush this in by EOD.

**Comment by MelissaAutumn** [comment]
Here you go @jfx2006 : https://start-stage.thunderbird.net/en-US/monthly/

Sorry it took so long.
