### ISSUE TITLE
Dead link (Explore Features)

### ISSUE THREAD

**Issue by pskidee** [thunderbird/thunderbird-website#620]
Dead link on email home page (Explore Features)

![image](https://github.com/user-attachments/assets/d2d74a76-0e82-441b-9507-2e4e7af323f8)

**Comment by wsmwk** [comment]
The link at account central goes to https://www.thunderbird.net/en-US/features/ which fails.

**Comment by MelissaAutumn** [comment]
Should be fixed when I push [this](https://github.com/thunderbird/thunderbird-website/commit/c2217aab6e1ec1b434be95d8b71d4259beeb3917 ) commit up to prod. Just didn't want to push it before the weekend :smile:

**Comment by MelissaAutumn** [comment]
This is now "fixed". We'll have a products page with features eventually, but for now it ships the user to the homepage which has the most information about Thunderbird.
