### ISSUE TITLE
Clearer phrasing on post-donation/download page

### ISSUE THREAD

**Issue by LinuxForEveryone** [thunderbird/thunderbird-website#625]
The _Thank You_ message currently at https://www.thunderbird.net/en-GB/thank-you/ can be confusing due to the line "Just One More Step." The 2nd line is also below the fold on certain resolutions, adding to that confusion. Since there is technically no call to action or click required at this stage, I'm proposing we change this text to:

"Thank You! [For Donating" if this is a post-donation page]
[Graphic]
"Now finish installing, and start enjoying Thunderbird."

**Comment by wsmwk** [comment]
Much better. Thanks.

**Comment by MelissaAutumn** [comment]
Np, should be on prod by eod I hope!

**Comment by LinuxForEveryone** [comment]
Thanks a bunch, Mel!
