### ISSUE TITLE
The release notes for 128.0.1 is a blank page

### ISSUE THREAD

**Issue by davidfromnewyork** [thunderbird/thunderbird-website#626]
Here is url for release notes: 
https://support.mozilla.org/en-US/questions/1453912#answer-1663674   and there are no notes

**Comment by wsmwk** [comment]
https://www.thunderbird.net/en-US/thunderbird/128.0.1esr/releasenotes/ works fine

**Comment by davidfromnewyork** [comment]
No, it’s not working. See attach. was reported on SUMO.

**Comment by davidfromnewyork** [comment]
My error on initial report; I shared wrong URL. Here is url from the about pane:
https://www.thunderbird.net/en-US/thunderbird/128.0.1/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=128.0.1&channel=esr&os=WINNT&buildid=20240717233102

**Comment by MelissaAutumn** [comment]
Hi @davidfromnewyork

**Comment by wsmwk** [comment]
The support request is https://support.mozilla.org/en-US/questions/1454147

works  esr 115.13.0 https://www.thunderbird.net/en-US/thunderbird/115.13.0/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=115.13.0&channel=esr&os=WINNT&buildid=20240715172621

fails  esr 128.0.1   https://www.thunderbird.net/en-US/thunderbird/128.0.1/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=128.0.1&channel=esr&os=WINNT&buildid=20240717233102

**Comment by wsmwk** [comment]
The full description to reproduce, is it fails from Help > About > Release Notes

**Comment by MelissaAutumn** [comment]
Hey @davidfromnewyork thanks for the report! This has been fixed, and the caching on our end has been cleared. 

However due to various other levels of caching (dns, browser, etc...) it could take up to 24 hours for the changes to appear on your end.

**Comment by davidfromnewyork** [comment]
Thanks for the kind words, but I could have done better. This was my  first issue to report , and I reported the wrong URL and failed to define from where I got the error. The fix would have gone more quickly, had I been thorough in reporting it. My thanks to you for addressing it so promptly.

david

**Comment by MelissaAutumn** [comment]
No worries we all make mistakes, including me..who has made a few this morning already 🤔 

Have a good day 😄 
Mel
