### ISSUE TITLE
release notes links from version 115.13.0 and previous version go to 404 pages

### ISSUE THREAD

**Issue by briangmoore77** [thunderbird/thunderbird-website#627]
when you go to the the about thunderbird panel in versions 115.13.0 (and the version before) and click the release notes link or the what's new link they both lead to a "There's Nothing Here" / "The page you are looking for doesn’t exist." page... I would call it a 404 page.

so here is the release notes link
https://www.thunderbird.net/en-US/thunderbird/115.13.0esr/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=115.13.0&channel=esr&os=WINNT&buildid=20240715172621

Here is the previsou version release notes link
https://www.thunderbird.net/en-US/thunderbird/115.12.2esr/releasenotes/?uri=/thunderbird/releasenotes/&locale=en-US&version=115.12.2&channel=esr&os=WINNT&buildid=20240621154414

**Comment by antdude** [comment]
Yep, https://www.thunderbird.net/en-US/thunderbird/115.13.0esr/releasenotes/ is missing. https://www.thunderbird.net/en-US/thunderbird/115.13.0/releasenotes/ works though, but it's not ESR.

**Comment by MelissaAutumn** [comment]
Remaining work at https://github.com/thunderbird/thunderbird-website/issues/619

Will close this once that is merged and up.

**Comment by MelissaAutumn** [comment]
Hello all, thanks for the reports!

I've re-worked the releases page and pushed it up. 
https://www.thunderbird.net/en-US/thunderbird/releases/

Cheers,
Mel
