### ISSUE TITLE
Website thunderbird.net/calendar does not offer any contents anymore

### ISSUE THREAD

**Issue by devvv4ever** [thunderbird/thunderbird-website#630]
This web page 

`https://www.thunderbird.net/calendar/`

had some information about TBs calendar integration, but now it is empty. Is this by intention or can we expect some content there in the future?

**Comment by MelissaAutumn** [comment]
Hello!

The information ended up being outdated as that page was originally made for when Thunderbird's calendar was a separate addon you had to install:
https://web.archive.org/web/20200613171631/https://www.thunderbird.net/en-US/calendar/

As of a couple years ago the calendar was brought into the main thunderbird codebase, and that page isn't really needed. In the future there will be a product page for Desktop and Mobile which should include a brief overview of Thunderbird's features.

If you were wondering about holiday calendars they're still available via the site's footer or here: https://www.thunderbird.net/en-US/calendar/holidays/

**Comment by devvv4ever** [comment]
Hi, thanks for the information. I was just asking because we were linking to this page from davx5.com because many of our users are using TB calendar via CalDAV on desktop. Holiday calendars could be interesting for ICSx5. Thank you!

**Comment by MelissaAutumn** [comment]
Ah I see! I would link to the main homepage: https://www.thunderbird.net as we do feature the calendar on the homepage laptop slideshow. We'll hopefully have a desktop product page in the near future.

Cheers
