### ISSUE TITLE
There's Nothing Here 115.11.1

### ISSUE THREAD

**Issue by metaad** [thunderbird/thunderbird-website#632]
https://www.thunderbird.net/en-US/thunderbird/115.11.1/releasenotes/

Above link says the page does not contain anything.

Also, Not able to find installers for the version 115.11.1 now.

Earlier we were able to download.

Is it pulled back? Any security concerns involved or is it safer to use ??

**Comment by Sancus** [comment]
Versions of 115 starting with 115.10.2 are now labeled ESR: https://www.thunderbird.net/en-US/thunderbird/115.11.1esr/releasenotes/

We'll add a redirect for 115, considering it switched in the middle of its run that is a little confusing. For 128.0 and later you will need to make sure you have the correct links.
