### ISSUE TITLE
Add a redirect that makes 115.# and 115.#esr interchangeable starting with 115.10.2

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-website#633]
People are getting confused by this, and given we switched in the middle it seems reasonable to have this redirect in the transition period.

We will not do this for 128.0 or later.

**Comment by MelissaAutumn** [comment]
Fixed: https://www.thunderbird.net/en-US/thunderbird/115.11.1/releasenotes/ -> https://www.thunderbird.net/en-US/thunderbird/115.11.1esr/releasenotes/

https://www.thunderbird.net/en-US/thunderbird/115.11.1/system-requirements/ -> https://www.thunderbird.net/en-US/thunderbird/115.11.1esr/system-requirements/
