### ISSUE TITLE
Not latest 32bit version is downloaded

### ISSUE THREAD

**Issue by Fredaker** [thunderbird/thunderbird-website#634]
When I try to download the latest 32-bit exe from https://www.thunderbird.net/en-US/thunderbird/all/, it downloads version 115.14.0 instead of 128.1.0. The 64-bit version downloads correctly.

![image](https://github.com/user-attachments/assets/6d9d988f-4347-486e-b1cf-ca4aa863d6cc)

**Comment by MelissaAutumn** [comment]
Thanks for the report, I have a fix that's being pushed up to our stage server. Once I do a quick check there I will push it up to prod!

**Comment by MelissaAutumn** [comment]
This should be fixed now! I've cleared the cache manually for a few languages but will otherwise clear up in a couple of hours.
