### ISSUE TITLE
Holiday calendar for Taiwan uses inappropriate character set

### ISSUE THREAD

**Issue by donnch** [thunderbird/thunderbird-website#646]
The calendar for Taiwan is using Simplified Characters. This is incorrect (and politically insulting) for Taiwanese users. The official writing system of Taiwan is [Traditional Characters](https://en.wikipedia.org/wiki/Traditional_Chinese_characters).

**Comment by MelissaAutumn** [comment]
Thank you for the report, and apologies for the incorret locale. I'll investigate this next week and regenerate the calendars accordingly.

**Comment by MelissaAutumn** [comment]
Hey there @donnch apologies for the delay. After checking with our calendar provider they don't seem to support Traditional Characters. Would English be an appropriate alternative?

**Comment by MelissaAutumn** [comment]
Hello again!

We're investigating switching calendar providers, which won't happen for a little while but wanted to check in. 

Would this data acceptable be acceptable? 
https://github.com/commenthol/date-holidays/blob/master/data/countries/TW.yaml

**Comment by donnch** [comment]
> Would English be an appropriate alternative?

Hi @MelissaAutumn , thanks for looking into this. I don't think I can comment on the extent to which other users would fully accept English instead (given it isn't the normal language), other than that it is at least a more palatable choice for some users who would find Simplified Characters to be an unnecessary reminder of geopolitical threats. I guess you could try changing to English temporarily and seeing if the number of subscribers to that calendar changed? 

The Wikipedia-based data in the link you suggested would be a suitable alternative as far as I can see, so hopefully new providers could be implemented sooner rather than later.

**Comment by MelissaAutumn** [comment]
Apologies for the delay and the less than ideal solution for now. But I've updated the calendar to use English in the mean-time. The website cache should clear in a few hours to a day.

We actually don't track subscription numbers for the calendar, and we'll hopefully switch providers in the near future. Let me know if there's anymore issues with the calendar!

**Comment by janbrasna** [comment]
I actually have a sample from another provider, that looks like proper Traditional Chinese: https://github.com/janbrasna/thunderbird-website/blob/fe68215/media/caldata/autogen/TaiwanHolidays.ics

@donnch @petercpg Would you be able to check this holiday calendar makes sense to you? Appreciate it.

**Comment by petercpg** [comment]
> I actually have a sample from another provider, that looks like proper Traditional Chinese: https://github.com/janbrasna/thunderbird-website/blob/fe68215/media/caldata/autogen/TaiwanHolidays.ics
> 
> [@donnch](https://github.com/donnch) [@petercpg](https://github.com/petercpg) Would you be able to check this holiday calendar makes sense to you? Appreciate it.

Hi, it looks better to me, while a few latest holiday changes should be updated. 

There are also some holiday names added with suffixes such as (Celebrate) `（慶祝）` (`2025-04-04 兒童節（慶祝）`, in contrast to `2027-04-04 兒童節`) or `Day off (replaces from 2025-02-08)` (`2025-01-27 休息日（2025-02-08日起取代）` which doesn't make sense to me. Probably bad translation.

There are also some holidays/commemorative days are missed from this iCal, but I don't think all missed ones are really required. Back in the Lightning days I think we just commit files but do we have a criteria on this now?


--

> Hello again!
> 
> We're investigating switching calendar providers, which won't happen for a little while but wanted to check in.
> 
> Would this data acceptable be acceptable? https://github.com/commenthol/date-holidays/blob/master/data/countries/TW.yaml

https://github.com/commenthol/date-holidays/blame/master/data/countries/TW.yaml#L30
This line for LNY is also in Simplified Chinese. Probably need some revise on the holiday list too.

**Comment by janbrasna** [comment]
Thank you for the feedback! So I tried pulling newest data, and there indeed are some tiny changes to zh-TW: https://github.com/janbrasna/thunderbird-website/blob/83ad6ea3e30b3625a956a0ba3d625b836b37f932/media/caldata/autogen/TaiwanHolidays.ics (but it doesn't look like any confusion is removed, perhaps only reworded?)

**Comment by petercpg** [comment]
Hi @janbrasna it looks even better now. Latest public holidays that is off for all Taiwanese people by-law is now added in this revision, what we still missed are some public holidays, folk holidays, or commemorative days that is observed but not off by the general public. In printed calendars we usually see them but the date will not be in red. 

Regarding the confusion, I think it's this line - https://github.com/vacanza/holidays/blob/53853dfe1e76bd9e32b1521bd8be5e505c2e7937/holidays/locale/zh_TW/LC_MESSAGES/TW.po#L171

I'll try to send a PR to fix it.

**Comment by petercpg** [comment]
Just to note, here's the PR opened in upstream: https://github.com/vacanza/holidays/pull/3066

**Comment by janbrasna** [comment]
Lovely, this looks like a viable workflow, to be pointing communities towards an upstream calendar data project, and seek consensus there, with knowledgeable caldata project maintainers steering the change requests and data quality. Great to follow the process there, nice job!

When I get a chance I'll do another try build with v0.86 to see what the data looks like now, and will come back here with the preview to check up with y'all how it looks for you now. Thanks for the updates!
