### ISSUE TITLE
Email graphic web links incorrectly activate zoom instead of the link

### ISSUE THREAD

**Issue by MP-zzz** [thunderbird/thunderbird-website#648]
I run Thunderbird v130.0 (64-bit) ‘Nebula’ on my Windows 10 Pro desktop PC
and Thunderbird v115.15 (64-bit) ‘Supernova’ on my Windows 10 Pro laptop

In the message pane in v130, hovering the mouse pointer over any images that incorporate links would usually activate the pointing finger pointer to action the link over which it's hovering. However, for a while now, the mouse pointer appears as a magnifying glass and simply magnifies the graphic image. This is nothing to do with poorly constructed emails, as this affects any email containing graphic links. I run Thunderbird v115 on my laptop and none of the very same emails behave in this way, rather the correct pointing finger is activated. However, text-based links in v130 on my desktop do activate the pointing finger pointer.

**Comment by MelissaAutumn** [comment]
Hello! This page is for bugs with the website thunderbird.net, you can file bugs for the desktop application over on bugzilla.

https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird

Thank you for your report!
