### ISSUE TITLE
 Czech Holidays Calendar - Strange Entries

### ISSUE THREAD

**Issue by janjanousek** [thunderbird/thunderbird-website#649]
Originally described as https://bugzilla.mozilla.org/show_bug.cgi?id=1920297:

Steps to reproduce:

I subscribed https://www.thunderbird.net/media/caldata/CzechHolidays.ics from https://www.thunderbird.net/en-US/calendar/holidays/#C (years ago).

Actual results:

Today, I found, this Czech Holidays calendar does not contain the holidays in Czechia. Newly, it contains a strange mixture of the holidays and some other days, some of them with mis-leading titles and descriptions.

E.g. January 1 shall be "Nový rok" (OK), and "Den obnovy samostatného českého státu" (not "Obnovení Dne nezávislosti České republiky"), February 14 ("Den svatého Valentýna") is not a holiday at all, etc.

Expected results:

The https://www.thunderbird.net/media/caldata/CzechHolidays.ics calendar shall follow the official Czech holidays, found e.g. on the https://en.wikipedia.org/wiki/Public_holidays_in_the_Czech_Republic page, and/or the https://www.mpsv.cz/svatky-v-ceske-republice page (just in Czech), with the proper titles.

The attached CzechHolidays.ics calendar might be used...
[CzechHolidays.ics.zip](https://github.com/user-attachments/files/17094900/CzechHolidays.ics.zip)

**Comment by MelissaAutumn** [comment]
Apologies I've removed the excess/non-holidays from the calendars. However looks like the improper localization remains. We're looking at switching calendar providers to one that is open-source and can be contributed to in the near-future and don't have the capacity to review/use community contributed calendars. 

Thank you for your report and patience!
