### ISSUE TITLE
Dead link to holiday calendars on support page

### ISSUE THREAD

**Issue by graue70** [thunderbird/thunderbird-website#652]
The last sentence on https://support.mozilla.org/de/kb/neue-kalender-erstellen contains a link to https://www.thunderbird.net/calendar/holidays/. When I follow the link, the page tells me this:

> There's Nothing Here
The page you are looking for doesn’t exist.
If you think this is a bug, you can [report an issue here](https://github.com/thunderbird/thunderbird-website/issues)

**Comment by MelissaAutumn** [comment]
Thank you for the report! I've submitted a patch for review. 

Once it's approved and deployed I will follow up and close this issue.
