### ISSUE TITLE
Global search fails

### ISSUE THREAD

**Issue by sibelman** [thunderbird/thunderbird-website#653]
Finding a message that is hiding in some folder has been a valuable feature, but it now fails.  Searching (CTRL-SHIFT-F) an entire mailbox generates a status message ("Searching...") but never finishes.  This worked well in previous versions, notwithstanding the 12GB size of my mailbox.  In 128.2.3esr 64-bit, it's broken.

O/S: Kubuntu 24.04
H/W: Intel Core i7, 16GB RAM, solid state storage

Note: I was sure I posted this recently, but cannot find it.  Sorry if it's a duplicate.

**Comment by Sancus** [comment]
This is the bug tracker for the Thunderbird website, not for Thunderbird desktop. You're looking for Bugzilla:

https://bugzilla.mozilla.org/enter_bug.cgi?format=guided&product=Thunderbird&component=Untriaged
