### ISSUE TITLE
Excessive Entries from Thunderbird Holiday Calendar for Germany

### ISSUE THREAD

**Issue by germede** [thunderbird/thunderbird-website#658]
**Problem:**

I've noticed that multiple clients (Nextcloud, Thunderbird desktop, Android (ICSx5), and potentially others) are receiving an excessive number of calendar entries from the Thunderbird public calendar for holidays in Germany. This is in contrast to the expected display of officially recognized holidays.

**Details:**

* **Affected Clients:** Nextcloud, Thunderbird desktop, Android (ICSx5), and potentially others
* **Calendar:** Thunderbird public calendar for holidays in Germany ([https://support.mozilla.org/en-US/kb/adding-a-holiday-calendar](https://support.mozilla.org/en-US/kb/adding-a-holiday-calendar)) (Specific URL: **[https://www.thunderbird.net/media/caldata/GermanHolidays.ics](https://www.thunderbird.net/media/caldata/GermanHolidays.ics)**)
* **Issue:** Multiple clients are displaying entries that are not officially recognized holidays at the state or federal level. These entries often commemorate events or days that many are not interested in.
* **Subscription Method:** Nextcloud provides a direct link to subscribe to the calendar from Thunderbird, which is how I've subscribed on all devices.

**Expected Behavior:**

All clients should display the same set of calendar entries (the Android client is getting somehow more of those entries), consistent with the officially recognized holidays in Germany.

**Example:**

![Screenshot from 2024-10-04 10-09-57](https://github.com/user-attachments/assets/a2666a45-fbce-4c41-bb91-f2502b640df7)

**Comment by MelissaAutumn** [comment]
Heya! Thanks for the report.

I believe it's due to the fact we pull "Observance" holidays in. Next time I regenerate the calendars (next week I believe, it's quarterly.) I can look at dropping that type, and see if it removes some of the fluff. 

Do you have examples of German holidays that shouldn't show up so I can spot check?

Also we'll probably swap to a different calendar provider in the future, which might switch things up again (for the better hopefully.)

Cheers

**Comment by germede** [comment]
Hey there and thanks for your reply ;)

Sure, 
![Screenshot_20241004-203738](https://github.com/user-attachments/assets/773e409e-890f-4db2-abdf-9244b89fc6a7)
AFAIK none of these entries is actually a public holiday (also not at state level). Many of them have category "Hebrew" or "Christian", some of them relate to the ending of daylight saving time (category "Clock change/Daylight Saving TIme"), some are just random like Weltsparsamkeitstag (World Thrift Day, category "Observance"). One of them in December is not translated well: "Tag des zerbrochenen Glasgedenkens". But the one "Reformationstag" at 31st October is actually a public holiday in some states but has category "Christian", so I think filtering them all out would be also not really a solution.

One further courious thing is: I'm getting many more of those entries in Android via ICSx5 compared to Thunderbird client. Maybe it is filtering out some categories as you mentioned... but there at Thunderbird client some important ones are missing, that are actually public holidays.

Nice to know you may switch calendar provider in the future, that may be a more suitable solution for this as well. Just wanted to report this 👍

**Comment by MelissaAutumn** [comment]
Hopefully we can get on that switch sooner-than-later. But I've updated the calendars for the quarter. Let me know if there's any lingering issues. Thanks!
