### ISSUE TITLE
German Holiday calendar has duplicated uids

### ISSUE THREAD

**Issue by mkmelin** [thunderbird/thunderbird-website#663]
https://bugzilla.mozilla.org/show_bug.cgi?id=1921465#c4 has the details.
Seems there's some issue with the autogeneration?

**Comment by liayn** [comment]
Just for the sake of completeness: Also Austrian calendar is affected

**Comment by AntonLydike** [comment]
It appears that all calendars are affected, picking random calendars yields duplicated UIDS.

**Comment by MelissaAutumn** [comment]
This should be fixed, a coding error didn't append the year to the end of the uuid. The website cache should clear in a day-or-so. 

Thanks for the report!

**Comment by MelissaAutumn** [comment]
np! happened to be the day I handle the quaterly calendar updates. 😄

**Comment by liayn** [comment]
For the record: Fixed with https://github.com/thunderbird/thunderbird-website/commit/6a1391b874604efed3258443fbb30a73b93c8e05#diff-2ce4496d5b604f5d35a34aace404c1ef913f1b3bb0b4866a5265019bfcf4213cR57
