### ISSUE TITLE
RSS not working

### ISSUE THREAD

**Issue by ymespejo** [thunderbird/thunderbird-website#666]
All RSS feed URLs have been lost.
![Thunderbird_RSS](https://github.com/user-attachments/assets/cc04cc87-a47d-4b3b-9b00-959951ce247d)
RSS feeds have not been syncing since September 26th. 
In the last three updates of Thunderbird, RSS feeds do not work

**Comment by Sancus** [comment]
This is the bug tracker for the Thunderbird website only. File bugs on Bugzilla:

https://bugzilla.mozilla.org/enter_bug.cgi?format=guided&product=Thunderbird&component=Untriaged
