### ISSUE TITLE
Update Donor Support Intake Form

### ISSUE THREAD

**Issue by mccormacklisa** [thunderbird/thunderbird-website#676]
We've revised this Form Assembly form to reflect updated language and revised picklist options.

I'm not sure what you need @MelissaAutumn to publish on the website so let me know if something else I should pull from Form Assembly. Attaching screenshot of options:
<img width="835" alt="Screenshot 2024-10-24 at 1 43 40 PM" src="https://github.com/user-attachments/assets/7131afcd-ae11-4f5a-925a-21995308df23">

**New form url:** 
https://mozillafoundation.tfaforms.net/89

**Javascript for Quick Publish**
<script src="https://mozillafoundation.tfaforms.net/publish/89" data-qp-target-id="" defer></script>

**Comment by MelissaAutumn** [comment]
Thanks I'll have to look at this later next week if that's alright.

**Comment by mccormacklisa** [comment]
Yup. Perfectly fine. Thanks!

**Comment by MelissaAutumn** [comment]
And this should be live within a day or two.
