### ISSUE TITLE
Change release channel start page

### ISSUE THREAD

**Issue by coreycb** [thunderbird/thunderbird-website#677]
Let's remove the warning page from the Thunderbird release channel.

Now that we are releasing monthly releases to the release channel, we are finding this warning is causing users more problems than it's worth as they attempt to downgrade from the current monthly to esr. At this point, the release channel is not much different than beta.

We can replace:
https://github.com/thunderbird/thunderbird-website/blob/master/sites/start.thunderbird.net/monthly/index.html

with something similar to what we have for beta:
https://github.com/thunderbird/thunderbird-website/blob/master/sites/start.thunderbird.net/beta/index.html

Eventually, once the release channel is considered stable, we can update it again.

**Comment by MelissaAutumn** [comment]
Seems simple enough. Is next week okay for this?

**Comment by Sancus** [comment]
We can just copy the release page and add a gentle warning banner to the top like Beta has. This is not urgent at all though, we can worry about it after the appeal and Android stuff is live.

**Comment by coreycb** [comment]
@MelissaAutumn Just checking in and wanted to see when you think this might get done. We had some more users tripping over this warning page last week. Thanks :)
