### ISSUE TITLE
Adjust store links on new mobile page

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-website#678]
The app store links currently using com.fsck.k9 need updating for the release, as follows:

**Play Store**:
https://play.google.com/store/apps/details?id=net.thunderbird.android&referrer=utm_campaign%3Dandroid_website_appeal%26utm_medium%3Dweb%26utm_source%3Dthunderbird.net%26utm_content%3Dlink

(replace link with button if a button, yes the encoded URL in the referrer parameter is correct)

**F-droid**:

May not be completed at launch time. Please comment out the f-droid buttons, but prepare the URL as follows:

https://f-droid.org/packages/net.thunderbird.android

**Comment by kewisch** [comment]
Same for https://stage.thunderbird.net/en-US/thunderbird/all/

**Comment by MelissaAutumn** [comment]
This is live on stage: https://stage.thunderbird.net/mobile and https://stage.thunderbird.net/thunderbird/all

f-droid link has been updated but is commented out for now. Please let me know tomorrow if you want this uncommented for Wednesday. 

Will close once this is on prod.

**Comment by MelissaAutumn** [comment]
This is live
