### ISSUE TITLE
Use tfa campaign tag on mobile pages on new site

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-website#679]
I see for example the small "Donate" link in "Free forever. Donate to make it better." points to `form=support`. I imagine we'd want to change this to `form=tfa`. I'm not sure how that works with other donate links on the page, are we able to change them all to `tfa` but only when on the mobile page?

**Comment by MelissaAutumn** [comment]
And finished. All donate buttons on https://stage.thunderbird.net/mobile/ are now set to tfa. Additionally the post-download redirect (is fixed and) also sets the correct form_id. 

Will close once this goes live on prod.

**Comment by MelissaAutumn** [comment]
This is live
