### ISSUE TITLE
Recent Update Redirects To "There's Nothing Here" page

### ISSUE THREAD

**Issue by nickyfr33ze** [thunderbird/thunderbird-website#683]
Updating to version 132.0, on reboot the page brings the following URL 
[There's Nothing Here - Thunderbird](https://www.thunderbird.net/en-US/thunderbird/132.0/whatsnew/?locale=en-US&version=132.0&channel=release&oldversion=131.0.1) : https://www.thunderbird.net/en-US/thunderbird/132.0/whatsnew/?locale=en-US&version=132.0&channel=release&oldversion=131.0.1

**Comment by Sancus** [comment]
Yeah that's definitely a releng bug.

**Comment by coreycb** [comment]
Thanks all. I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1928399 for this issue.

**Comment by MelissaAutumn** [comment]
Thanks! I'll close this issue here.
