### ISSUE TITLE
Add copy of donate button to bottom of Nov24 appeal

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-website#684]
We agreed there should be a button there, so there's still a CTA after you've scrolled down.

@laurelterlesky has some ideas of how to do it simply.

This should be a copy of one of the existing buttons with no new strings or images.

**Comment by MelissaAutumn** [comment]
What we ended up on:
<img width="788" alt="image" src="https://github.com/user-attachments/assets/6cbfba6c-b0ad-4e4b-a8ba-681f8d80e5ad">

Will be merged onto prod in a min.

**Comment by Sancus** [comment]
Nice work.

**Comment by Sancus** [comment]
Also, we should give that a unique utm code so that we can see how popular it ends up being, I'm sure you've already thought of that :)

**Comment by MelissaAutumn** [comment]
`utm_content=bottom-cta` 😄

**Comment by MelissaAutumn** [comment]
And live!
