### ISSUE TITLE
Add f-droid download links

### ISSUE THREAD

**Issue by kewisch** [thunderbird/thunderbird-website#687]
Here are the two links. I think we already had a badge, let me know if not.

https://f-droid.org/packages/net.thunderbird.android

https://f-droid.org/packages/net.thunderbird.android.beta

**Comment by MelissaAutumn** [comment]
Coming to a production server near you!
<img width="524" alt="image" src="https://github.com/user-attachments/assets/c09f43f2-d956-4d11-ad1b-39efe3221129">

**Comment by MelissaAutumn** [comment]
It's live:
https://www.thunderbird.net/download/
