### ISSUE TITLE
About Thunderbird "What's New"

### ISSUE THREAD

**Issue by Big-Al-NH** [thunderbird/thunderbird-website#689]
According to "Help -> About Thunderbird", my current version is 115.10.1 (64-bit) and the current version is 116.0. I wanted to see what was new in 116 so I clicked on "What's New", and was brought to:

https://www.thunderbird.net/en-US/thunderbird/128.4.1esr/releasenotes/

which says "There's Nothing Here".

**Comment by Sancus** [comment]
The release notes are updated now.
