### ISSUE TITLE
Mobile QR Code Generator does not working

### ISSUE THREAD

**Issue by ilkemt** [thunderbird/thunderbird-website#690]
After I enter to the "Export accounts to Thunderbird Mobile" from the settings, when I press the export button, nothing happens, the QR code does not appear.

**Comment by Sancus** [comment]
Hi, this repository is for website bugs not bugs in Thunderbird desktop or Thunderbird mobile.

Desktop bugs should be filed on Bugzilla: https://bugzilla.mozilla.org/enter_bug.cgi?format=guided&product=Thunderbird&component=Untriaged
