### ISSUE TITLE
Copy Nov24 appeal to 115 folder

### ISSUE THREAD

**Issue by Sancus** [thunderbird/thunderbird-website#695]
Also change the UTM tag a bit so we can see if there's any difference in donations between 128 and 115, while we're at it.

**Comment by MelissaAutumn** [comment]
I'm going to re-open this to have both 115 templates extend off of the 128 one, and do any utm changes in jinja variables on monday.

**Comment by Sancus** [comment]
Good point on the duplication, but I don't think any utm changes are necessary other than the campaign, which I already changed.

Maybe donation_base_url needs to be changed, though.

**Comment by Sancus** [comment]
I feel like this donate_button macro would work better if, instead of taking parameters like `source`, it instead used template-level variables like `utm_source`, but only if they were set.  So like, at the top of the macro do something like

`{% set utm_source = utm_source|default('thunderbird-client') %}` etc.

That way you would not need to change the button call in the template when re-using the template for different things.

**Comment by Sancus** [comment]
I've moved the client version information to the source variable for now.
