### ISSUE TITLE
Make privacy links easier for google to find

### ISSUE THREAD

**Issue by radishmouse** [thunderbird/thunderbird-website#707]
There is a potential issue with the way that the privacy policy is linked, leading to Google not being able to locate the privacy policy. 

The result is that users of ~Thunderbird for Android and~ K-9 Mail cannot log into their google accounts:
* https://forum.k9mail.app/t/yet-another-issue-with-gmail/10992* 
* ~https://github.com/thunderbird/thunderbird-android/issues/8598~

The proposed solution is to:
* update `sites/www.thunderbird.net/includes/base/footer.html` so there is only 1 privacy link
* add a sidebar `sites/www.thunderbird.net/privacy/index.html` that includes links to the thunderbird privacy policy and the mozilla privacy policy

Edited: only K9 is affected

**Comment by lockon-stratos-x4** [comment]
> There is a potential issue with the way that the privacy policy is linked, leading to Google not being able to locate the privacy policy.The result is that users of Thunderbird for Android and K-9 Mail cannot log into their google accounts

The latest version of Thunderbird and the beta version can register Gmail without problems.
Only K9 cannot be registered.
