### ISSUE TITLE
add a link to the thunderbird source code and the bug tracker for non-English visitors too

### ISSUE THREAD

**Issue by Yvan-Masson** [thunderbird/thunderbird-website#72]
Hi,

As said in the issue title, I think it would be very interesting to have links to the source code (and I mean the VCS) and to the bug tracker.

Thanks for your time and work,
Yvan

**Comment by Sancus** [comment]
There is already a link to the source at the bottom of the page, "Contribute to this site." I'm somewhat skeptical of linking to the issue tracker specifically because I suspect it will just produce a lot of duplicates, but I'll consider it for the 404 page at least.

**Comment by Yvan-Masson** [comment]
I am sorry, I did not explain well my issue: there is no link to source code/bug tracker for **Thunderbird itself**.

Regards,
Yvan

**Comment by Sancus** [comment]
Yeah there is. https://www.thunderbird.net/en-US/get-involved/

**Comment by Sancus** [comment]
No, that's intentional because we think some level of ability to understand English is necessary to contribute and we are definitely not equipped to handle a significant number of bug reports in non-English languages on our bug tracker or other contributor communication systems(mailing lists, etc).

I would consider letting the menu link to the english-language page appear on those pages, but I'm pretty sure localizers would then want to translate the page and we don't want that at this time.

cc @ryanleesipes

**Comment by Yvan-Masson** [comment]
OK, thanks for the explanation. I perfectly understand that you do not want / can not translate everything.

On the other hand, for everybody that does not use English as main language, it is very frustrating to not be able to find those technical information. I even thought that this was a non official website… (yes I am very suspicious when browsing :-) ) For "technical" people, I think it is very important to have this information, particularly after the separation of Mozilla and Thunderbird.

In any case, many thanks for this good software!

**Comment by mkmelin** [comment]
This seems like quite an oversight, that we should fix. 
I suggest we add the get involved link to all localizations, but on top of the get-involved page check referer and if not English, put a notice explaining that the project communication is in English and you need some basic English skills to interact, therefore the following information is not localized.

**Comment by Yvan-Masson** [comment]
That would be perfect!

**Comment by MelissaAutumn** [comment]
The new website finally fixes this issue:
https://www.thunderbird.net/fr/participate/

**Comment by Yvan-Masson** [comment]
Thanks!
