### ISSUE TITLE
Empty "from x to y" webpage

### ISSUE THREAD

**Issue by NetBender** [thunderbird/thunderbird-website#721]
Hi, 
I just updated from 132.0.1 to 133.0 and, after a restart, Thunderbird opened an empty [changelog webpage](https://www.thunderbird.net/en-US/thunderbird/133.0/whatsnew/?locale=it&version=133.0&channel=release&oldversion=132.0.1)

<img src="https://github.com/user-attachments/assets/a777fc61-42fc-4163-9979-6d62a13e6314" width="600" />

**Comment by MelissaAutumn** [comment]
Hey there, where did you orginally download Thunderbird? Was it from your distro or from thunderbird.net?

**Comment by NetBender** [comment]
I am running Thunderbird on Windows 11. Last week, I moved from ESR to the Release channel by downloading the latest .exe from the website.

**Comment by nunyafukkinbizness** [comment]
Same problem: Updated from 128.4 to 128.5 Ubuntu![Image](https://github.com/user-attachments/assets/a69e6fb5-d2b2-41f4-94f6-8b815d95119f)
 clicked on Help>about Thunderbird>Release Notes I got sent to "There's Nothing Here" page. Please update Thunderbird to have the correct release notes page or have empty page with links to the release notes. Thanks!

**Comment by MelissaAutumn** [comment]
Thank you, this is being looked into.

**Comment by MelissaAutumn** [comment]
Hello! the whatsnew pages shouldn't be showing up on monthly release builds, and I believe this is fixed. Please open a new ticket if this happend again.

Thanks again for your reports!
